In [2]:
import pandas as pd 
import os 
import glob
import numpy as np

import pickle

In [2]:
path = "/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/hausa_newsclass/files"
all_files = glob.glob(os.path.join(path, "*.csv"))

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

combined = pd.concat(li, axis=0, ignore_index=True)

In [35]:
train_df = pd.read_csv(os.path.join(path, "train.csv"))
test_df = pd.read_csv(os.path.join(path, "test.csv"))

In [46]:
train_df_ft = pd.read_csv("/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/hausa_newsclass/features/Hausa_train_features.csv", header=None)
test_df_ft = pd.read_csv("/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/hausa_newsclass/features/Hausa_test_features.csv", header=None)

In [7]:
combined["label"].value_counts()

1    1980
4     751
3     642
2     202
0     177
Name: label, dtype: int64

In [16]:
df_t = pd.read_csv("/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/hausa_newsclass/files/train_noisy.tsv", sep="\t", header=0)

In [17]:
df_test = pd.read_csv("/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/hausa_newsclass/files/test.tsv", sep="\t", header=0)

In [21]:
df_dev = pd.read_csv("/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/hausa_newsclass/files/dev.tsv", sep="\t", header=0)

In [22]:
combined_t = pd.concat([df_t, df_test, df_dev], axis=0, ignore_index=True)

In [23]:
len(combined_t)

4042

In [24]:
combined_t["label"].value_counts()

World       2060
Africa       796
Nigeria      705
Health       264
Politics     217
Name: label, dtype: int64

In [52]:
X_train = train_df_ft.to_numpy()
y_train = train_df["label"].to_numpy()

In [53]:
X_test = test_df_ft.to_numpy()
y_test = test_df["label"].to_numpy()

In [54]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((3170, 768), (3170,), (582, 768), (582,))

In [55]:
from imblearn.over_sampling import SMOTE

In [56]:
smote = SMOTE("minority")

# error in tutorial, this needs to be resample, not sample
X_sm, y_sm = smote.fit_resample(X_train, y_train)

/home/maha.agro/thesis/bert_lnl/BERT-LNL/bert_lnl0/lib/python3.8/site-packages/imblearn/utils/_validation.py:586: FutureWarning: Pass sampling_strategy=minority as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [57]:
X_sm.shape, y_sm.shape

((4912, 768), (4912,))

In [60]:
y_sm[-1]

2

In [62]:
import numpy as np

In [63]:
np.savetxt("Hausa_train_features_balanced.csv", X_sm, delimiter=",")

In [64]:
np.savetxt("Hausa_train_labels.csv", y_sm, delimiter=",")

# Formatting Yoruba Dataset

In [7]:
# split into train, validation, test, txt
path = "/home/maha.agro/thesis/bert_lnl/BERT-LNL/data"

In [8]:
# create a label to idx file 
# check labels in yoruba 
os.path.join(path, "/Yoruba/csv_data/train_clean_noisy_labels.csv")

'/Yoruba/csv_data/train_clean_noisy_labels.csv'

In [9]:
# first get the texts in train_clean_noisy
# save each document per line 
# read file in pandas data frame 

yoruba_train = pd.read_csv('/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/Yoruba/csv_data/train_clean_noisy_labels.csv')
yoruba_train

news_title  label
0     Xenophobic Attack: Awọn ọmọ Nàìjíria tí yarí p...      0
1     Árẹ̀wá: Bákan náà ni a kò fẹ́ Atiku torí dúkìá...      3
2     2019 Election update: Buhari borí; ó di ààrẹ N...      3
3     Nathaniel Samuel: Ìwádìí tí bẹ̀rẹ̀ lórí afuras...      5
4     Yoruba Film: Ṣé ẹ máa wá ní Pasuma ni mo bí àw...      4
...                                                 ...    ...
1335  BB Naija 2019: Ọlọ́pàá Gẹ̀ẹ́sì bẹ̀rẹ̀ ìwádìí l...      4
1336  End of a decade: Àwọn ìròyìn mẹ́wàá tó mí ilẹ̀...      1
1337  Electoral bill 2018: Èrèèdí wàhálà láàárín Buh...      3
1338  Onitsha market fire: Ilé tó lé ni 100 ló bá ìṣ...      1
1339  Election Tribunal: INEC ní òfin kò ní kí èsì ì...      3

[1340 rows x 2 columns]

In [10]:
labels = set(yoruba_train["label"].values)

In [9]:
labels 

{'africa', 'entertainment', 'health', 'nigeria', 'politics', 'sport', 'world'}

In [32]:
# creating a dictionary, 0 indexing 
lb2idx = {"africa": 0, "nigeria": 1, "health": 2, "politics": 3, "entertainment": 4, "sport": 5, "world": 6}

In [33]:
with open("/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/Yoruba/txt_data/lb2idx.pickle", "wb") as lb2idx_file:
        pickle.dump(lb2idx, lb2idx_file)

In [34]:
idx2lb = {0: "africa", 1: "nigeria", 2: "health", 3: "politics", 4: "entertainment", 5: "sport", 6: "world"}

In [35]:
with open("/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/Yoruba/txt_data/idx2lb.pickle", "wb") as idx2lb_file:
        pickle.dump(idx2lb, idx2lb_file)

In [14]:
yoruba_train["news_title"].values

array(['Xenophobic Attack: Awọn ọmọ Nàìjíria tí yarí pé àwọn náà yóò gbẹ̀san',
       'Árẹ̀wá: Bákan náà ni a kò fẹ́ Atiku torí dúkìá àjọni wà tó fẹ́ tà',
       '2019 Election update: Buhari borí; ó di ààrẹ Nàìjíríà tuntun',
       ...,
       'Electoral bill 2018: Èrèèdí wàhálà láàárín Buhari àtàwọn aṣòfin àpapọ̀ lórí òfin ìdìbò 2018',
       'Onitsha market fire: Ilé tó lé ni 100 ló bá ìṣẹ̀lẹ̀ ìjàmbá iná lọ ní Onitsha',
       "Election Tribunal: INEC ní òfin kò ní kí èsì ìbò ààrẹ wà lórí ''server''"],
      dtype=object)

In [15]:
np.savetxt("/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/Yoruba/txt_data/train.txt", yoruba_train["news_title"].values, fmt="%s")

In [14]:
## Validation dataset

In [37]:
yoruba_val = pd.read_csv(os.path.join(path, "distant_supervision_dataset/yoruba_newsclass/dev.csv"))
yoruba_val

news_title  label
0    UNILAG Child Molestation: Ọ̀jọ̀gbọ́n Fagbohung...      1
1    9th Assembly: Dogara kìlọ̀ fáwọn ẹgbẹ́ òṣèlú l...      3
2    Illegal Rehab Centre: Feb 2008 ni wọ́n fẹ̀ṣùn ...      1
3    Omí pọ̀ ju ọkà lọ fún Unai Emery, ìfìdírẹ̀mi m...      5
4    Logo Benz: Ìtanijí ni orin wa wà fún, Ẹ má ká ...      4
..                                                 ...    ...
184  Shiite Movement: Shiite fèsì lórí àṣẹ ilé ẹjọ́...      1
185  9th Assembly: PDP ní láìpẹ́ làwọn aráàlú yóò m...      3
186  Adekunle Gold: Ọdún márùn ún ni mo fi mọ Simi ...      4
187  Biafra at 50: Ọ̀nà tí ẹja panla gbà di gbajúgb...      1
188  Death at Airport: Ọkùnrin kan jáde láyé bó ṣe ...      1

[189 rows x 2 columns]

In [17]:
np.savetxt("/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/Yoruba/txt_data/validation_clean.txt", yoruba_val["news_title"].values, fmt="%s")

In [38]:
yoruba_test = pd.read_csv(os.path.join(path, "distant_supervision_dataset/yoruba_newsclass/test.csv"))
yoruba_test

news_title  label
0       Àwọn ìgbà tí jándùkú òṣèlú tí wáyé ní Nàìjíríà      1
1    Tanko Mohammed: Agbẹjọ́rò 250 ni Adájọ́ Àgbà ṣ...      1
2    Boko Haram: Ilé iṣẹ́ ọmọogun kò sọ fún mi pé ọ...      1
3    SSANU, NASU gbé fásitì Ibadan tì pa nítorí ìya...      1
4    Tanker Fire: Eré àṣàpajúdé tí ọkọ́ epo náà sá ...      1
..                                                 ...    ...
374  Òbìnrin mánigbàgbé mẹ́ta nínú ìjọba tiwantiwa ...      3
375  Bauchi Elections: Gómínà Abubakar ti kí Mohamm...      3
376  Ọbanikoro: Àjọṣepọ̀ tó wà láàárín èmi àti Fayo...      3
377      Ladi Àdebutu ni olùdíje gómìnà wa l'Ogun —PDP      3
378  Àwọn wòòlí ń takora lórí ẹni tí yóò di ààrẹ lá...      3

[379 rows x 2 columns]

In [21]:
np.savetxt("/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/Yoruba/txt_data/test_clean.txt", yoruba_test["news_title"].values, fmt="%s")

In [14]:
yoruba_train_clean = pd.read_csv('/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/Yoruba/csv_data/train_clean.csv')
yoruba_train_clean

news_title  label
0     Xenophobic Attack: Awọn ọmọ Nàìjíria tí yarí p...      0
1     Árẹ̀wá: Bákan náà ni a kò fẹ́ Atiku torí dúkìá...      3
2     2019 Election update: Buhari borí; ó di ààrẹ N...      3
3     Nathaniel Samuel: Ìwádìí tí bẹ̀rẹ̀ lórí afuras...      1
4     Yoruba Film: Ṣé ẹ máa wá ní Pasuma ni mo bí àw...      4
...                                                 ...    ...
1335  BB Naija 2019: Ọlọ́pàá Gẹ̀ẹ́sì bẹ̀rẹ̀ ìwádìí l...      4
1336  End of a decade: Àwọn ìròyìn mẹ́wàá tó mí ilẹ̀...      4
1337  Electoral bill 2018: Èrèèdí wàhálà láàárín Buh...      3
1338  Onitsha market fire: Ilé tó lé ni 100 ló bá ìṣ...      1
1339  Election Tribunal: INEC ní òfin kò ní kí èsì ì...      3

[1340 rows x 2 columns]

In [23]:
np.savetxt("/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/Yoruba/txt_data/train_clean.txt", yoruba_train_clean["news_title"].values, fmt="%s")

## Pickling the labels

In [12]:
# pickle train labels 
# open train_clean_noisy_labels.csv 
# append all labels to a list 
# pickle the saved labels 
yoruba_train["label"].values

array([0, 3, 3, ..., 3, 1, 3])

In [13]:
with open("/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/Yoruba/train_clean_noisy_labels.pickle", "wb") as train_labels_file:
        pickle.dump(yoruba_train["label"].values.tolist(), train_labels_file)

In [42]:
yoruba_val["label"].values

array([1, 3, 1, 5, 4, 1, 1, 0, 1, 3, 1, 3, 2, 1, 2, 2, 1, 4, 1, 2, 1, 1,
       1, 1, 1, 1, 3, 1, 1, 3, 1, 1, 1, 6, 4, 3, 6, 1, 3, 6, 3, 6, 1, 1,
       1, 0, 1, 1, 1, 4, 0, 3, 3, 4, 1, 1, 3, 0, 3, 1, 1, 3, 4, 1, 4, 1,
       2, 1, 4, 6, 0, 1, 4, 1, 3, 1, 1, 3, 4, 4, 1, 1, 3, 4, 3, 3, 1, 6,
       3, 3, 1, 4, 3, 0, 5, 1, 3, 4, 3, 0, 3, 0, 1, 4, 3, 3, 4, 3, 1, 1,
       4, 4, 4, 1, 3, 1, 1, 1, 4, 3, 2, 3, 3, 4, 1, 0, 6, 0, 1, 1, 1, 4,
       3, 6, 1, 5, 3, 4, 4, 3, 6, 4, 4, 4, 4, 4, 1, 5, 4, 4, 0, 1, 6, 3,
       3, 3, 1, 3, 0, 3, 1, 3, 3, 4, 0, 1, 1, 1, 4, 5, 3, 5, 1, 4, 3, 6,
       3, 1, 3, 6, 1, 5, 1, 2, 1, 3, 4, 1, 1])

In [43]:
with open("/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/Yoruba/txt_data/validation_clean_labels.pickle", "wb") as val_labels_file:
        pickle.dump(yoruba_val["label"].values.tolist(), val_labels_file)

In [44]:
yoruba_test["label"].values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,

In [45]:
with open("/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/Yoruba/txt_data/test_clean_labels.pickle", "wb") as test_labels_file:
        pickle.dump(yoruba_test["label"].values.tolist(), test_labels_file)

In [16]:
yoruba_train_clean["label"].values

array([0, 3, 3, ..., 3, 1, 3])

In [17]:
with open("/home/maha.agro/thesis/bert_lnl/BERT-LNL/data/Yoruba/train_clean_labels.pickle", "wb") as train_clean_labels_file:
        pickle.dump(yoruba_train_clean["label"].values.tolist(), train_clean_labels_file)